language: node_js
node_js:
  - 12
  - 10

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run deploy

deploy:
  provider: npm
  email: $npm_mail
  api_key: $npm_key
  tag: next
  on:
    tags: true
