language: node_js
node_js:
  - 14

script:
  - npm run test

before_install:
  - npm install -g npm@8.7.0

before_deploy:
  - npm run build
  - npm run predeploy

deploy:
  - provider: npm
    skip_cleanup: true
    email: $npm_mail
    api_key: $npm_key
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $github_key
    keep_history: true
    local_dir: 'example/build'
    on:
      tags: true
