language: node_js
node_js:
  - 12

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run predeploy

deploy:
  - provider: npm
    email: $npm_mail
    api_key: $npm_key
  - provider: pages
    skip_cleanup: true
    github_token: $github_key
    keep_history: true
    local_dir: 'example/build'
  on:
    tags: true
