language: node_js
node_js:
  - 12
  - 10

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: '$npm_mail'
  api_key: '$npm_key'
  on:
    tags: true

after_deploy:
  - npm run deploy
