language: node_js
node_js:
  - 12
  - 10

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run predeploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_key
  keep_history: true
  local_dir: example/build
  provider: npm
  email: $npm_mail
  api_key: $npm_key
  tag: next
  on:
    tags: true
