language: node_js
node_js:
  - 12

install:
  - npm install
  - npm i -g npm-run-all
  - npm i -g microbundle-crl
  - npm i -g cross-env
  - npm i -g react-scripts
  - npm i -g node-dass
  - npm i -g @material-ui/core

script:
  - npm run test

before_deploy:
  - npm run build
  - npm run predeploy

deploy:
  - provider: npm
    email: $npm_mail
    api_key: $npm_key
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $github_key
    keep_history: true
    local_dir: 'example/build'
    on:
      tags: true
